services:
 backend:
  build:
   context: ./
   dockerfile: Dockerfile
  image: i-verifity # Especifica el nombre de la imagen
  container_name: c-veritify # Especifica el nombre del contenedor
  env_file:
   - .prod.env
  ports:
   - "5000:5000"
  depends_on:
   - database

 database:
  image: mongo:latest
  container_name: mongodb
  ports:
   - "27018:27017"
  restart: always
  volumes:
   - /home/mongo-data/veritify:/data/db
