services:
 backend:
  build:
   context: ./
   dockerfile: Dockerfile
  image: image-verifity # Especifica el nombre de la imagen
  container_name: container-veritify # Especifica el nombre del contenedor
  env_file:
   - .prod.env
  ports:
   - "5000:5000"
  depends_on:
   - mongo

 mongo:
  image: mongo:latest
  restart: always
  container_name: mongo-veritify
  environment:
   MONGO_INITDB_DATABASE: veritify
  ports:
   - "27017:27017"
  volumes:
   - ./mongo-data:/data/db
   - ./mongo-data/log:/var/log/mongodb/
