services:
 backend:
  build:
   context: ./
   dockerfile: Dockerfile
  image: image-verifity # Especifica el nombre de la imagen
  container_name: container-veritify # Especifica el nombre del contenedor
  env_file:
   - .prod.env
  ports:
   - "5000:5000"
  depends_on:
   - mongo

 mongo:
  image: mongo:latest
  container_name: mongo-veritify
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: rootpassword
   MONGO_INITDB_DATABASE: veritify
   MONGO_INITDB_USERNAME: admin
   MONGO_INITDB_PASSWORD: AdminAdminAdmin
  ports:
   - "27018:27017"
  volumes:
   - mongo-data:/data/db
  command: >
   bash -c '
   mongod --auth --bind_ip_all --fork --logpath /var/log/mongodb.log &&
   mongo admin --eval "db.createUser({ user: '\''admin'\'', pwd: '\''AdminAdmin'\'', roles: [{ role: '\''readWrite'\'', db: '\''veritify'\'' }] })" &&
   mongod --shutdown &&
   mongod --auth --bind_ip_all
   '

volumes:
 mongo-data:
